-- Creates the restaurants and menu_items tables to match our entity classes.
-- Note: BOOLEAN is a native Oracle 23c+ type - use NUMBER(1) instead if
-- targeting an older Oracle version (see swiggy-user-service notes).

CREATE TABLE restaurants (
    id            NUMBER(19)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id      NUMBER(19)      NOT NULL,
    name          VARCHAR2(150)   NOT NULL,
    address       VARCHAR2(255)   NOT NULL,
    city          VARCHAR2(100)   NOT NULL,
    cuisine_type  VARCHAR2(100),
    rating        NUMBER(2,1)     DEFAULT 0.0,
    is_open       BOOLEAN         DEFAULT TRUE NOT NULL,
    created_at    TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at    TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_restaurants_city ON restaurants(city);
CREATE INDEX idx_restaurants_owner ON restaurants(owner_id);

CREATE TABLE menu_items (
    id            NUMBER(19)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id NUMBER(19)      NOT NULL,
    name          VARCHAR2(150)   NOT NULL,
    description   VARCHAR2(500),
    price         NUMBER(10,2)    NOT NULL,
    category      VARCHAR2(50)    NOT NULL,
    is_available  BOOLEAN         DEFAULT TRUE NOT NULL,

    CONSTRAINT fk_menu_items_restaurant
        FOREIGN KEY (restaurant_id) REFERENCES restaurants(id)
        ON DELETE CASCADE,
    CONSTRAINT chk_menu_items_category
        CHECK (category IN ('STARTER','MAIN_COURSE','DESSERT','BEVERAGE'))
);

CREATE INDEX idx_menu_items_restaurant ON menu_items(restaurant_id);