-- ===================================================================
-- Swiggy Restaurant Service - Initial Schema
-- Migration: V1__create_restaurants_table.sql
-- ===================================================================

-- Flyway runs migrations in order: V1, V2, V3...

CREATE TABLE restaurants (
    -- Primary key: auto-incrementing number
    id            NUMBER(19)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Foreign key to User Service (NOT a real FK, just a number)
    -- Why not FOREIGN KEY constraint? Because users table is in different schema
    owner_id      NUMBER(19)      NOT NULL,
    
    -- Basic info
    name          VARCHAR2(200)   NOT NULL,
    address       VARCHAR2(500)   NOT NULL,
    city          VARCHAR2(100)   NOT NULL,
    
    -- GPS coordinates for distance calculations
    -- Latitude: -90 to +90, Longitude: -180 to +180
    latitude      NUMBER(10, 7)   NOT NULL,  -- 7 decimal places = ~1cm accuracy
    longitude     NUMBER(10, 7)   NOT NULL,
    
    -- Business details
    cuisine_type  VARCHAR2(100)   NOT NULL,
    rating        NUMBER(3, 2)    DEFAULT 0.0 NOT NULL,  -- 0.00 to 5.00
    is_open       BOOLEAN         DEFAULT TRUE NOT NULL,
    
    -- Audit timestamps
    created_at    TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at    TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    
    -- Unique constraint: One owner cannot have two restaurants with same name
    -- But different owners CAN have restaurants with same name
    CONSTRAINT uq_restaurants_owner_name UNIQUE (owner_id, name),
    
    -- Check constraint: Rating must be 0-5
    CONSTRAINT chk_rating CHECK (rating >= 0 AND rating <= 5)
);

-- Index for filtering by city (common query: "restaurants in Pune")
CREATE INDEX idx_restaurants_city ON restaurants(city);

-- Index for filtering by cuisine (common query: "North Indian restaurants")
CREATE INDEX idx_restaurants_cuisine ON restaurants(cuisine_type);

-- Index for finding restaurants by owner (common query: "my restaurants")
CREATE INDEX idx_restaurants_owner ON restaurants(owner_id);

-- Composite index for common combined filter
CREATE INDEX idx_restaurants_city_cuisine ON restaurants(city, cuisine_type);