-- This file is run automatically by Flyway when the app starts,
-- creating the "users" table to match our User.java entity.

CREATE TABLE users (
    id            NUMBER(19)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name     VARCHAR2(150)   NOT NULL,
    email         VARCHAR2(150)   NOT NULL,
    password_hash VARCHAR2(255)   NOT NULL,
    phone_number  VARCHAR2(20),
    role          VARCHAR2(30)    NOT NULL,
    is_active     BOOLEAN         DEFAULT TRUE NOT NULL,
    created_at    TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at    TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT chk_users_role CHECK (role IN ('CUSTOMER','RESTAURANT_OWNER','DELIVERY_PARTNER','ADMIN'))
);

-- Speeds up queries that filter by role, e.g. "get all delivery partners"
CREATE INDEX idx_users_role ON users(role);